name: veracode-scan
on: [push]

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
    - name: print values
      run: |
          git log -1
          echo "${{ github.event.workflow_run.head_commit.message }}"
