name: veracode-scan
on: [push]

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
    - name: commit
      run: |
          # Get last commit message
            readonly local last_commit_log=$(git log -1 --pretty=format:"%s")
            echo "last commit log: $last_commit_log"
