name: veracode-scan
on: [push]

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
    - name: print values
      env:
        commit_msg: ${{ github.event.workflow_run.head_commit.message }}
      run: echo ${{ github.event.workflow_run.head_commit.message }}
